language: erlang
otp_release:
  - 19.3
before_script:
  - rebar get-deps
script: rebar compile
after_script:
  - rebar clean
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
